/* Copyright (c) 1996, 2002, 2004 by Arkkra Enterprises */
/* All rights reserved. */

#ifdef EXTCHAR

/* Define the extended (non-ASCII) characters */
/* Mapping between name and number is done via Ext_char_table[] */

#define C_exclamdown 	(32)	
#define C_cent 		(33)	
#define C_sterling 	(34)	
#define C_yen 		(35)	
#define C_quotedblleft 	(36)	
#define C_guillemotleft 	(37)	
#define C_guillemotright 	(38)	
#define C_guilsinglleft 	(39)	
#define C_guilsinglright 	(40)	
#define C_dagger 	(41)	
#define C_daggerdbl 	(42)	
#define C_bullet 	(43)	
#define C_quotedblbase 	(44)	
#define C_quotedblright 	(45)	
#define C_questiondown 	(46)	
#define C_grave 	(47)	
#define C_acute 	(48)	
#define C_macron 	(49)	
#define C_breve 	(50)	
#define C_dotaccent 	(51)	
#define C_dieresis 	(52)	
#define C_ring 		(53)	
#define C_cedilla 	(54)	
#define C_hungarumlaut 	(55)	
#define C_ogonek 	(56)	
#define C_caron 	(57)	
#define C_emdash 	(58)	
#define C_AE 		(59)	
#define C_ae 		(60)	
#define C_ordfeminine 	(61)	
#define C_ordmasculine 	(62)	
#define C_Lslash 	(63)	
#define C_lslash 	(64)	
#define C_Oslash 	(65)	
#define C_oslash 	(66)	
#define C_OE 		(67)	
#define C_oe 		(68)	
#define C_dotlessi 	(69)	
#define C_germandbls 	(70)	
#define C_Aacute 	(71)	
#define C_aacute 	(72)	
#define C_Acircumflex 	(73)	
#define C_acircumflex 	(74)	
#define C_Adieresis 	(75)	
#define C_adieresis 	(76)	
#define C_Agrave 	(77)	
#define C_agrave 	(78)	
#define C_Aring 	(79)	
#define C_aring 	(80)	
#define C_Atilde 	(81)	
#define C_atilde 	(82)	
#define C_Ccedilla 	(83)	
#define C_ccedilla 	(84)	
#define C_Eacute 	(85)	
#define C_eacute 	(86)	
#define C_Ecircumflex 	(87)	
#define C_ecircumflex 	(88)	
#define C_Edieresis 	(89)	
#define C_edieresis 	(90)	
#define C_Egrave 	(91)	
#define C_egrave 	(92)	
#define C_Iacute 	(93)	
#define C_iacute 	(94)	
#define C_Icircumflex 	(95)	
#define C_icircumflex 	(96)	
#define C_Idieresis 	(97)	
#define C_idieresis 	(98)	
#define C_Igrave 	(99)	
#define C_igrave 	(100)	
#define C_Ntilde 	(101)	
#define C_ntilde 	(102)	
#define C_Oacute 	(103)	
#define C_oacute 	(104)	
#define C_Ocircumflex 	(105)	
#define C_ocircumflex 	(106)	
#define C_Odieresis 	(107)	
#define C_odieresis 	(108)	
#define C_Ograve 	(109)	
#define C_ograve 	(110)	
#define C_Otilde 	(111)	
#define C_otilde 	(112)	
#define C_Scaron 	(113)	
#define C_scaron 	(114)	
#define C_Uacute 	(115)	
#define C_uacute 	(116)	
#define C_Ucircumflex 	(117)	
#define C_ucircumflex 	(118)	
#define C_Udieresis 	(119)	
#define C_udieresis 	(120)	
#define C_Ugrave 	(121)	
#define C_ugrave 	(122)	
#define C_Ydieresis 	(123)	
#define C_ydieresis 	(124)	
#define C_Zcaron 	(125)	
#define C_zcaron 	(126)	
#define C_space 	(127)	

#endif
